<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<OutputType>Library</OutputType>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<EnableDefaultCompileItems>true</EnableDefaultCompileItems>
		<RootNamespace>GameScripts</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<OutputPath>../build/bin/Debug/</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<OutputPath>../build/bin/Release/</OutputPath>
	</PropertyGroup>

</Project>